### ISSUE TITLE
Clean project not works after updating to latest version

### ISSUE THREAD

**Issue by suaterken** [SqrTT/prophet#100]
Hi, 
Today i have updated VS code to latest version 1.22.1
and after, extension started to give me those error messages when i try to clean project

Error: TypeError: Cannot set property '_value' of undefined

Error: Error: EPERM: operation not permitted, stat '...\bc_csc_actions_cartridge.zip'

**Comment by zeeshan1001** [comment]
I also get a similar issue after upgrade here is the log:


bc_library] Sending zip to remote
Error: TypeError: Cannot set property '_value' of undefined
Error: TypeError: Cannot set property '_value' of undefined
	at e.report (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:380:634)
	at SafeSubscriber.webdav.uploadCartridge.do [as _complete] (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/out/server/uploadServer.js:78:13)
	at SafeSubscriber.wrappedComplete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:222:76)
	at SafeSubscriber.__tryOrSetError (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:248:16)
	at SafeSubscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:228:26)
	at Subscriber._complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:133:26)
	at Subscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:115:18)
	at DoSubscriber._complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/operators/tap.js:103:24)
	at DoSubscriber.Subscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:115:18)
	at FilterSubscriber.Subscriber._complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:133:26)
	at FilterSubscriber.Subscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:115:18)
	at MergeMapSubscriber.notifyComplete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/operators/mergeMap.js:167:30)
	at InnerSubscriber._complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/InnerSubscriber.js:30:21)
	at InnerSubscriber.Subscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:115:18)
	at CatchSubscriber.Subscriber._complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:133:26)
	at CatchSubscriber.Subscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:115:18)
	at DoSubscriber._complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/operators/tap.js:108:30)
	at DoSubscriber.Subscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:115:18)
	at MergeMapSubscriber.notifyComplete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/operators/mergeMap.js:167:30)
	at InnerSubscriber._complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/InnerSubscriber.js:30:21)
	at InnerSubscriber.Subscriber.complete (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/rxjs/Subscriber.js:115:18)
	at Request.request [as _callback] (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/out/server/WebDav.js:19:30)
	at Request.self.callback (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/request/request.js:186:22)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/request/request.js:1163:10)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (/Users/zpe/.vscode/extensions/SqrTT.prophet-1.0.4/node_modules/request/request.js:1085:12)
	at Object.onceWrapper (events.js:293:19)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by SqrTT** [comment]
please remove files *<cart_name>_cartridge.zip* from each cartridge

**Comment by suaterken** [comment]
Yeah and also we can't open zipped files, seems there is some problems occured after latest update.

**Comment by zeeshan1001** [comment]
The problem is still there tried everything mentioned above.

**Comment by suaterken** [comment]
We have downgraded to 1.21.1 till problem is resolved

**Comment by zeeshan1001** [comment]
How can we downgrade ?

**Comment by suaterken** [comment]
Remove/reinstall vs code ?

**Comment by SqrTT** [comment]
Could you please update the extension to `v1.0.5` and check if it's fixed for you?

**Comment by suaterken** [comment]
Thank you! What a great effort
