### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by mgloder** [SqrTT/prophet#105]
Hi I'm using prophet to upload my cartridges to my sandbox. 
Sometimes, it will generate some erros like this:
```
[app_storefront_base] Deleting remote zip...
Error: Error: read ECONNRESET
Trying to re-upload
Connection validated successfully
Current active version is: develop-2
```
after that sometimes, it will generate:
```
Error: Error: read ECONNRESET
Error: Error: read ECONNRESET
	at exports._errnoException (util.js:1050:11)
	at TLSWrap.onread (net.js:581:26)
```

Its look like something wrong with node?

OS: Ubuntu 16.04
Extension Version: 1.08
Node Version: v6.14.1
npm Version: 3.10.10

**Comment by SqrTT** [comment]
Does `dwupload` or Eclipse uploads correctly?

**Comment by ghgofort** [comment]
I am having the same issue or a similar issue today.  This is the first time that it has happened to me, but I have had it happen several times now.

**NOTE:** If this looks to be a separate connection issue, let me know, and I will file it as it's own issue.

## When it occurs:

- This seems to happen when I am making edits, after a save. The extension tries to clean all cartridges, and re-upload, but fails half way through.  
- If I disable upload, then re-enable, the issue still occurs.
- If I restart VSCode, the issue goes away, and all cartridges upload fine.
- Haven't found any pattern for file type or anything of that nature yet. I will update if I find anything out.

## Output channel:
```
Starting...
Using config file '/Users/galen.goforth/bitbucket/dw-upstream/cartridges/dw.json'
Connection validated successfully
Current active version is: upstream
Upload cartridges on start is disabled via config
Watching files
Restarting
Using config file '/Users/galen.goforth/bitbucket/dw-upstream/cartridges/dw.json'
Connection validated successfully
Current active version is: upstream
Start uploading cartridges
Cleanup code version...
Deleted app_loyalty
Deleted site_ugg_us
Deleted site_sanuk
Deleted site_hoka_v2
Deleted site_teva_sanuk
Deleted core_deckers
Deleted site_teva_us
Deleted app_spc
Deleted site_ugg_closet
Deleted core_commerce_richUI
Deleted int_DCD_avatax
Deleted int_accertify
Deleted app_returns
Deleted site_services
Deleted site_koolaburra
Deleted modules
Deleted int_paypal_v16_1_0
Deleted core_commerce
Deleted app_ordershippingstatus
Deleted core_controllers
[site_teva_sanuk] Deleting local zip
[site_teva_sanuk] Zipping
[app_loyalty] Deleting local zip
[app_loyalty] Zipping
[site_sanuk] Deleting local zip
[site_sanuk] Zipping
[core_deckers] Deleting local zip
[core_deckers] Zipping
[app_loyalty] Deleting remote zip
[app_loyalty] Sending zip to remote
[site_sanuk] Deleting remote zip
[site_teva_sanuk] Deleting remote zip
[core_deckers] Deleting remote zip
[site_sanuk] Sending zip to remote
[site_teva_sanuk] Sending zip to remote
[core_deckers] Sending zip to remote
[app_loyalty] Deleting local zip...
[app_loyalty] Unzipping remote zip
[app_loyalty] Deleting remote zip...
[site_teva_sanuk] Deleting local zip...
[site_teva_sanuk] Unzipping remote zip
[site_ugg_us] Deleting local zip
[site_ugg_us] Zipping
[site_teva_sanuk] Deleting remote zip...
[site_ugg_us] Deleting remote zip
[site_hoka_v2] Deleting local zip
[site_hoka_v2] Zipping
[site_ugg_us] Sending zip to remote
[site_hoka_v2] Deleting remote zip
[site_hoka_v2] Sending zip to remote
[site_sanuk] Deleting local zip...
[site_sanuk] Unzipping remote zip
[core_deckers] Deleting local zip...
[core_deckers] Unzipping remote zip
[site_sanuk] Deleting remote zip...
[core_controllers] Deleting local zip
[core_controllers] Zipping
[core_deckers] Deleting remote zip...
[core_controllers] Deleting remote zip
[app_returns] Deleting local zip
[app_returns] Zipping
[core_controllers] Sending zip to remote
[app_returns] Deleting remote zip
[app_returns] Sending zip to remote
[core_controllers] Deleting local zip...
[core_controllers] Unzipping remote zip
[core_controllers] Deleting remote zip...
[site_koolaburra] Deleting local zip
[site_koolaburra] Zipping
[app_returns] Deleting local zip...
[app_returns] Unzipping remote zip
[app_returns] Deleting remote zip...
[site_koolaburra] Deleting remote zip
[site_services] Deleting local zip
[site_services] Zipping
[site_services] Deleting remote zip
[site_koolaburra] Sending zip to remote
[site_services] Sending zip to remote
[site_services] Deleting local zip...
[site_services] Unzipping remote zip
[site_services] Deleting remote zip...
[site_ugg_closet] Deleting local zip
[site_ugg_closet] Zipping
[site_ugg_closet] Deleting remote zip
[site_ugg_closet] Sending zip to remote
[site_hoka_v2] Deleting local zip...
[site_hoka_v2] Unzipping remote zip
[site_ugg_us] Deleting local zip...
[site_ugg_us] Unzipping remote zip
[site_hoka_v2] Deleting remote zip...
[site_ugg_us] Deleting remote zip...
[app_spc] Deleting local zip
[app_spc] Zipping
[core_commerce_richUI] Deleting local zip
[core_commerce_richUI] Zipping
[app_spc] Deleting remote zip
[app_spc] Sending zip to remote
[core_commerce_richUI] Deleting remote zip
[core_commerce_richUI] Sending zip to remote
[site_koolaburra] Deleting local zip...
[site_koolaburra] Unzipping remote zip
[app_spc] Deleting local zip...
[app_spc] Unzipping remote zip
[site_ugg_closet] Deleting local zip...
[site_ugg_closet] Unzipping remote zip
[app_spc] Deleting remote zip...
[site_koolaburra] Deleting remote zip...
[int_accertify] Deleting local zip
[int_accertify] Zipping
[site_ugg_closet] Deleting remote zip...
[int_accertify] Deleting remote zip
[int_DCD_avatax] Deleting local zip
[int_DCD_avatax] Zipping
[int_accertify] Sending zip to remote
[modules] Deleting local zip
[modules] Zipping
[int_DCD_avatax] Deleting remote zip
[modules] Deleting remote zip
[modules] Sending zip to remote
[int_DCD_avatax] Sending zip to remote
[int_accertify] Deleting local zip...
[int_accertify] Unzipping remote zip
[int_accertify] Deleting remote zip...
[modules] Deleting local zip...
[modules] Unzipping remote zip
[int_DCD_avatax] Deleting local zip...
[int_DCD_avatax] Unzipping remote zip
[app_ordershippingstatus] Deleting local zip
[app_ordershippingstatus] Zipping
[app_ordershippingstatus] Deleting remote zip
[modules] Deleting remote zip...
[app_ordershippingstatus] Sending zip to remote
[site_teva_us] Deleting local zip
[site_teva_us] Zipping
[int_DCD_avatax] Deleting remote zip...
[app_ordershippingstatus] Deleting local zip...
[app_ordershippingstatus] Unzipping remote zip
[int_paypal_v16_1_0] Deleting local zip
[int_paypal_v16_1_0] Zipping
[site_teva_us] Deleting remote zip
[int_paypal_v16_1_0] Deleting remote zip
[app_ordershippingstatus] Deleting remote zip...
[site_teva_us] Sending zip to remote
[int_paypal_v16_1_0] Sending zip to remote
[core_commerce] Deleting local zip
[core_commerce] Zipping
[int_paypal_v16_1_0] Deleting local zip...
[int_paypal_v16_1_0] Unzipping remote zip
[int_paypal_v16_1_0] Deleting remote zip...
[core_commerce_richUI] Deleting local zip...
[core_commerce_richUI] Unzipping remote zip
[core_commerce_richUI] Deleting remote zip...
[core_commerce] Deleting remote zip
[site_teva_us] Deleting local zip...
[site_teva_us] Unzipping remote zip
[core_commerce] Sending zip to remote
[site_teva_us] Deleting remote zip...
[core_commerce] Deleting local zip...
[core_commerce] Unzipping remote zip
[core_commerce] Deleting remote zip...
Cartridges uploaded successfully
Watching files
[U 14:48:40] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce/cartridge/controllers/Email.js
[U 14:57:13] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/app_loyalty/cartridge/templates/default/loyalty/account/ecomm/user/registration.isml
[U 14:57:37] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/app_loyalty/cartridge/templates/default/loyalty/account/ecomm/user/registration.isml
[U 15:00:19] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/src/app/email-signup.js
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/site_ugg_us/cartridge/static/default/js/built/findstores.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/site_ugg_us/cartridge/static/default/js/built/findstores.min.js
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/android-pay.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/apple-pay.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/clickandcollect.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/lateloader.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/findstores.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/returns.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/searchresults.min.js.map
[U 15:00:25] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/android-pay.min.js
[U 15:00:26] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/apple-pay.min.js
[U 15:00:26] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/clickandcollect.min.js
[U 15:00:26] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/lateloader.min.js
[U 15:00:26] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/findstores.min.js
[U 15:00:26] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/returns.min.js
[U 15:00:26] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/searchresults.min.js
[U 15:00:26] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/apple-pay.min.js.map
[U 15:00:28] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/android-pay.min.js.map
[U 15:00:28] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/findstores.min.js.map
[U 15:00:28] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/clickandcollect.min.js.map
[U 15:00:28] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/lateloader.min.js.map
[U 15:00:28] /Users/galen.goforth/bitbucket/dw-upstream/cartridges/core_commerce_richUI/cartridge/static/default/js/built/searchresults.min.js.map
Error: Error: read ECONNRESET
Trying to re-upload
Connection validated successfully
Current active version is: upstream
Start uploading cartridges
Cleanup code version...
Error: Error: write EPROTO 140735678514048:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:659:

Trying to re-upload
Connection validated successfully
Current active version is: upstream
Start uploading cartridges
Cleanup code version...
Error: Error: write EPROTO 140735678514048:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:659:

Trying to re-upload
Connection validated successfully
Current active version is: upstream
Start uploading cartridges
Cleanup code version...
Deleted site_sanuk
Deleted int_DCD_avatax
Deleted site_hoka_v2
Deleted app_loyalty
Deleted site_teva_sanuk
Deleted core_controllers
Deleted site_ugg_us
Deleted app_returns
Deleted modules
Deleted int_accertify
Deleted site_ugg_closet
Deleted site_koolaburra
Deleted site_services
Deleted site_teva_us
Deleted app_spc
Deleted int_paypal_v16_1_0
Deleted core_commerce_richUI
Deleted app_ordershippingstatus
Error: Error: Internal Server Error
Error: Error: Internal Server Error
	at Request.request [as _callback] (/Users/galen.goforth/.vscode/extensions/SqrTT.prophet-1.0.10/out/server/WebDav.js:15:36)
	at Request.self.callback (/Users/galen.goforth/.vscode/extensions/SqrTT.prophet-1.0.10/node_modules/request/request.js:186:22)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (/Users/galen.goforth/.vscode/extensions/SqrTT.prophet-1.0.10/node_modules/request/request.js:1163:10)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (/Users/galen.goforth/.vscode/extensions/SqrTT.prophet-1.0.10/node_modules/request/request.js:1085:12)
	at Object.onceWrapper (events.js:293:19)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by ghgofort** [comment]
My issue appears to have been caused by a new firewall at work. After updating certificates, I am no longer having any issue.

**Comment by itsallrelative** [comment]
Started having this issue this morning as well. Had to change my active code version back and forth before it would upload correctly again.

**Comment by SqrTT** [comment]
Is the issue resolved?
