### ISSUE TITLE
EADDRINUSE error

### ISSUE THREAD

**Issue by Gektorian** [SqrTT/prophet#151]
```{"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"::","port":60606}```

```Unable open port for browsers files, probably other instance or Digital Studio is opened. Error: listen EADDRINUSE :::60606```

![image](https://user-images.githubusercontent.com/3693219/50283869-df85c180-045f-11e9-9edd-fd11876c6ac0.png)

In the same time, I have only 1 window of VSC and also Eclipse is closed.

**Comment by SqrTT** [comment]
Hi @Gektorian 
this error comes from OS. Try to kill all vscode process and then start (it could hang up even main process is killed) or restart OS.

**Comment by ayushiguptaappirio** [comment]
Hi, I am facing the same issue now.

**Comment by SqrTT** [comment]
Hi @ayushiguptaappirio 
Is eclipse or another instance of VS code running?

**Comment by ayushiguptaappirio** [comment]
No I am just using single instance code. Also, I see this error in debug console
Error: Unknown
    at Request.request [as _callback] (/.vscode/extensions/SqrTT.prophet-1.0.10/out/Connection.js:73:35)
    at Request.self.callback (/.vscode/extensions/SqrTT.prophet-1.0.10/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/.vscode/extensions/SqrTT.prophet-1.0.10/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/.vscode/extensions/SqrTT.prophet-1.0.10/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)Error: Unknown

**Comment by SqrTT** [comment]
you are using v1.0.10 while current is 1.3.20... please update your version to latest (update VS Code may be required)

**Comment by ayushiguptaappirio** [comment]
Hey, I tried to update VS Code too,but it is showing your Vs Code is updated, tried to uninstall and install the prophet extension too.

**Comment by ayushiguptaappirio** [comment]
Hey, I just restarted my laptop, it is working fine now. Anyway thanks for the help!!
