### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by dlopezSoul** [SqrTT/prophet#152]
Very often, when uploading cartridges, I am getting this error:

`Error: connect ETIMEDOUT XX.XXX.XX.XXX:YYY`

Then it automatically tries again:

```
Trying to re-upload
Connection validated successfully
Current active version is: 1_0_2
Start uploading cartridges
Cleanup code version...
Deleted app_storefront_checkout
Deleted app_storefront_mycartridge
Deleted app_storefront_core
Error: Error: connect ETIMEDOUT XX.XXX.XX.XXX:YYY
```
I can get the same error in a row a few times, until eventually it will just work:
```
Cartridges uploaded successfully
Watching files
```
But in some cases I get this error and it will stop retrying:
```
Error: Error: connect ETIMEDOUT XX.XXX.XX.XXX:YYY
Error: Error: connect ETIMEDOUT XX.XXX.XX.XXX:YYY
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
```

It won't happen always but it's so often it really slows us down.
Same thing is happening to a few developers working in the same project.

I have hidden IP addresses in this post for security reasons.

Is there a possible fix for this? Is this caused by the plugin or it's Salesforce's issue?

Thank you,
Daniel

**Comment by SqrTT** [comment]
Hi @dlopezSoul 
This looks like network issues. 
Try to use `ping`/`traceroute` detect where the problem is.

PS. The extension tries to upload 5 times. If face error more than 5 times, stops trying

**Comment by dlopezSoul** [comment]
Thank you very much for your answer @SqrTT 

That was my theory, and not only a theory it really looks like the cause of ETIMEDOUT error is based on a network issue which I guess I must talk with salesforce to solve since it's only happening in a particular project.

But something related with the plugin itself is that for some reason I can't alocate, Prophet uploader will start Uploading cartridges without me clicking on "upload cartridges".
This happen very often and because the network doesn't seem stable it make it even worse.

Any idea why would the plugin start uploading without me telling it to do so?

Thanks

**Comment by SqrTT** [comment]
the extension uploads all cartridges when upload some file fails (after several tries, 3 if I remember correctly). You should be able to see this in the logs. A reason of this is because extension tries to fix the state of cartridges on sandbox which may become corrupted after uploads.

**Comment by dlopezSoul** [comment]
I see! So if I modify a particular file, the autoupload configuration upload that specific file, but then it fails in the process, it won't display an error in the normal Prophet Upload's "OUTPUT" tab but it may have internally failed the upload, which after three tries force the upload cartridges, correct?
Ok that makes sense, thank you for that clarification.

If that's the case I assume it's all on Salesforce's servers's side and I guess it's with them to deal.

Thank you very much for all your help!

Daniel

**Comment by dlopezSoul** [comment]
Hi @SqrTT,

New information has arrived, we couldn't really work properly with all the ETIMEDOUT and eventually we tried going back to old school - uploading cartridges using **Eclipse** and turns out it works perfect! Not even a single timeout...

So I'm pretty sure there must be some misconfiguration on our project or something related to the Prophet Uploader that we are missing, and is definitely causing this. 

Any thoughts?

Thank you,
Daniel

**Comment by SqrTT** [comment]
Hi @dlopezSoul 
thank you input.

Could you please try to use `https://www.npmjs.com/package/dwupload` and see if it works? (VSCode relays on the same library to upload)

**Comment by dlopezSoul** [comment]
Hi @SqrTT 

I will tell the team to give that a try and come back to you.

Thank you very much!

Daniel
