### ISSUE TITLE
Error: SyntaxError

### ISSUE THREAD

**Issue by cloudzocker** [SqrTT/prophet#154]
Hi @SqrTT,
I am getting the following SyntaxError in OUTPUT:
```
Starting...
Error: SyntaxError: Unexpected token ] in JSON at position 258
Error: SyntaxError: Unexpected token ] in JSON at position 258
	at JSON.parse (<anonymous>)
	at ReadStream.rxjs_1.Observable.stream.on (/Users/********/.vscode/extensions/sqrtt.prophet-1.0.22/out/server/WebDav.js:363:35)
	at ReadStream.emit (events.js:182:13)
	at fs.close (fs.js:2202:14)
	at /Applications/VisualStudioCode.app/Contents/Resources/app/node_modules.asar/graceful-fs/graceful-fs.js:43:10
	at FSReqWrap.oncomplete (fs.js:169:20)
```
Using Visual Studio Code Version 1.31.0 (1.31.0) and Prophet Debugger 1.0.22
Appricate your help. Thanks a lot

**Comment by SqrTT** [comment]
looks like you have errors in your `dw.json`

**Comment by cloudzocker** [comment]
@SqrTT Thank you very much Anatolii! You are absolutely right!
Many thanks for your super fast response! 👍

**Comment by SqrTT** [comment]
you are welcome
