### ISSUE TITLE
Upload breaks when code version directory does not exist

### ISSUE THREAD

**Issue by SGD1953** [SqrTT/prophet#166]
Output is something like:
````
Starting...
Using config file '/.../playground/cartridges/dw.json'
Unable validate connection!
Validation error: Not Found 
Error: Error: Not Found 
Trying to re-upload
Unable validate connection!
Validation error: Not Found 
Error: Error: Not Found 
Trying to re-upload
Unable validate connection!
Validation error: Not Found 
Error: Error: Not Found 
Trying to re-upload
Unable validate connection!
Validation error: Not Found 
Error: Error: Not Found 
Error: Error: Not Found 
	at Request.rxjs_1.Observable.fromPromise.flatMap.rxjs_1.Observable.request [as _callback] (/Users/xxx/.vscode/extensions/sqrtt.prophet-1.1.2/out/server/WebDav.js:17:36)
	at Request.init.self.callback (/Users/xxx/.vscode/extensions/sqrtt.prophet-1.1.2/node_modules/request/request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.<anonymous> (/Users/xxx/.vscode/extensions/sqrtt.prophet-1.1.2/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:182:13)
	at IncomingMessage.<anonymous> (/Users/xxx/.vscode/extensions/sqrtt.prophet-1.1.2/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1090:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Hyune-kel** [comment]
Same problem for me...

**Comment by SqrTT** [comment]
fixed in 1.1.5. Feel free to reopen if reproduces.
