### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by pavlyukpetr** [SqrTT/prophet#185]
Hello,
I have the upload error. I am using Prophet for SFCC.

Error: Error: 
	at Request.rxjs_1.Observable.fromPromise.flatMap.rxjs_1.Observable.request [as _callback] (C:\Users\p.pavliuk\.vscode\extensions\sqrtt.prophet-1.1.9\out\server\WebDav.js:17:36)
	at Request.init.self.callback (C:\Users\p.pavliuk\.vscode\extensions\sqrtt.prophet-1.1.9\node_modules\request\request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.<anonymous> (C:\Users\p.pavliuk\.vscode\extensions\sqrtt.prophet-1.1.9\node_modules\request\request.js:1161:10)
	at Request.emit (events.js:182:13)
	at IncomingMessage.<anonymous> (C:\Users\p.pavliuk\.vscode\extensions\sqrtt.prophet-1.1.9\node_modules\request\request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1092:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)

Please, help. Thanks.

**Comment by SqrTT** [comment]
Hi @pavlyukpetr
Thank you for reporting.

Looks like for some reason sandbox returns error >= 400.
Unfortunately I see no reason why it does that...

Is there a way to reproduce it?

**Comment by pavlyukpetr** [comment]
Hello, @SqrTT 
I fixed the issue by installing the version 1.1.6

Looks like something wrong with the latest versions.

**Comment by SqrTT** [comment]
latest versions don't have changes in uploading logic

**Comment by Strongground** [comment]
I have come across the same error.
Stacktrace:
```
Error: Error: 
	at Request.rxjs_1.Observable.fromPromise.flatMap.rxjs_1.Observable.request [as _callback] (/Users/noel/.vscode/extensions/sqrtt.prophet-1.1.9/out/server/WebDav.js:17:36)
	at Request.init.self.callback (/Users/noel/.vscode/extensions/sqrtt.prophet-1.1.9/node_modules/request/request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.<anonymous> (/Users/noel/.vscode/extensions/sqrtt.prophet-1.1.9/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:182:13)
	at IncomingMessage.<anonymous> (/Users/noel/.vscode/extensions/sqrtt.prophet-1.1.9/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1092:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

Last successful upload to sandbox was last week Monday.

**Comment by SqrTT** [comment]
hi all,
Could you share error message from 1.2.0 version of extension, please?

**Comment by SqrTT** [comment]
seems to issue is not actual anymore, please feel free to reopen if I'm wrong
