### ISSUE TITLE
Version 1.2.2 - 400 Bad Request on Clean Project/Upload All Command

### ISSUE THREAD

**Issue by davishd** [SqrTT/prophet#196]
**Describe the bug**
After installing version 1.2.2, I receive a 400 Bad Request error while running the _Clean Project/Upload All_ command. I can revert back to version 1.2.1 and it works without error.

**To Reproduce**
1. Install Version 1.2.2
2. Run _Prophet: Clean Project/Upload All_ command
3. See error

**Expected behavior**
It should upload as expected.

**Screenshots**
See console output below.

**Desktop (please complete the following information):**
 - OS: macOS 10.15 (19A583) **Catalina**
 - VSCode version 1.39.2
 - Extension version 1.2.2

**Additional context**
```
Restarting
Using config file '/Users/davisdevries/src/dw.json'
Connection validated successfully
Current active version is: ddevries
Start uploading cartridges
Cleanup code version...
[cartridgeA] Deleting remote zip (if any)
[cartridgeA] Zipping
[cartridgeB] Deleting remote zip (if any)
[cartridgeB] Zipping
[build_tools] Deleting remote zip (if any)
[build_tools] Zipping
[cartridgeC] Deleting remote zip (if any)
[cartridgeC] Zipping
[cartridgeA] Sending zip to remote
[cartridgeB] Sending zip to remote
[build_tools] Sending zip to remote
[cartridgeC] Sending zip to remote
[cartridgeB] Remove remote cartridge before extract
Error: Error: Bad Request 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>404 URL Not Found</title>
	<link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
	<h1>URL Not Found</h1>
	<img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
	<p class="system_info">
		The requested URL was not found on this server.
	</p>
	<hr>
</body>
</html>


{
    "response": {
        "statusCode": 400,
        "body": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n<head>\n\t<title>404 URL Not Found</title>\n\t<link rel=\"STYLESHEET\" type=\"text/css\" href=\"/waroot/style.css\">\n</head>\n<body>\n\t<h1>URL Not Found</h1>\n\t<img src=\"/waroot/system_arrow.gif\" width=\"21\" height=\"21\" alt=\"\" border=\"0\">\n\t<p class=\"system_info\">\n\t\tThe requested URL was not found on this server.\n\t</p>\n\t<hr>\n</body>\n</html>\n\n",
        "headers": {
            "content-type": "text/html;charset=UTF-8",
            "content-length": "400",
            "date": "Mon, 21 Oct 2019 15:52:23 GMT",
            "connection": "close",
            "server": "Apache"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "dev10.demandware.net",
                "port": 443,
                "hostname": "dev10.demandware.net",
                "hash": null,
                "search": null,
                "query": null,
                "pathname": "/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC",
                "path": "/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC",
                "href": "https://dev10.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC"
            },
            "method": "DELETE",
            "headers": {
                "authorization": "Basic PASSWORD",
                "content-length": 0
            }
        }
    },
    "request": {
        "baseUrl": "https://dev10.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges/ddevries",
        "uri": "/../../../../../../../cartridgeC",
        "auth": {
            "user": "ddevries@dev.com",
            "password": "PASSWORD",
            "pass": "PASSWORD"
        },
        "strictSSL": false,
        "method": "DELETE"
    }
}
Trying to re-upload
Connection validated successfully
Current active version is: ddevries
Start uploading cartridges
Cleanup code version...
[cartridgeC] Deleting remote zip (if any)
[cartridgeC] Zipping
[bm_tools] Deleting remote zip (if any)
[bm_tools] Zipping
[int_powerreviews_sfra] Deleting remote zip (if any)
[int_powerreviews_sfra] Zipping
[build_tools] Deleting remote zip (if any)
[build_tools] Zipping
[int_powerreviews_sfra] Sending zip to remote
[bm_tools] Sending zip to remote
[cartridgeC] Sending zip to remote
[build_tools] Sending zip to remote
[int_powerreviews_sfra] Remove remote cartridge before extract
[bm_tools] Remove remote cartridge before extract
Error: Error: Bad Request 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>404 URL Not Found</title>
	<link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
	<h1>URL Not Found</h1>
	<img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
	<p class="system_info">
		The requested URL was not found on this server.
	</p>
	<hr>
</body>
</html>


{
    "response": {
        "statusCode": 400,
        "body": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n<head>\n\t<title>404 URL Not Found</title>\n\t<link rel=\"STYLESHEET\" type=\"text/css\" href=\"/waroot/style.css\">\n</head>\n<body>\n\t<h1>URL Not Found</h1>\n\t<img src=\"/waroot/system_arrow.gif\" width=\"21\" height=\"21\" alt=\"\" border=\"0\">\n\t<p class=\"system_info\">\n\t\tThe requested URL was not found on this server.\n\t</p>\n\t<hr>\n</body>\n</html>\n\n",
        "headers": {
            "content-type": "text/html;charset=UTF-8",
            "content-length": "400",
            "date": "Mon, 21 Oct 2019 15:52:23 GMT",
            "connection": "close",
            "server": "Apache"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "dev10.demandware.net",
                "port": 443,
                "hostname": "dev10.demandware.net",
                "hash": null,
                "search": null,
                "query": null,
                "pathname": "/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC",
                "path": "/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC",
                "href": "https://dev10.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC"
            },
            "method": "DELETE",
            "headers": {
                "authorization": "Basic PASSWORD",
                "content-length": 0
            }
        }
    },
    "request": {
        "baseUrl": "https://dev10.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges/ddevries",
        "uri": "/../../../../../../../cartridgeC",
        "auth": {
            "user": "ddevries@dev.com",
            "password": "PASSWORD",
            "pass": "PASSWORD"
        },
        "strictSSL": false,
        "method": "DELETE"
    }
}
Error: Error: Bad Request 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>404 URL Not Found</title>
	<link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
	<h1>URL Not Found</h1>
	<img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
	<p class="system_info">
		The requested URL was not found on this server.
	</p>
	<hr>
</body>
</html>


{
    "response": {
        "statusCode": 400,
        "body": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n<head>\n\t<title>404 URL Not Found</title>\n\t<link rel=\"STYLESHEET\" type=\"text/css\" href=\"/waroot/style.css\">\n</head>\n<body>\n\t<h1>URL Not Found</h1>\n\t<img src=\"/waroot/system_arrow.gif\" width=\"21\" height=\"21\" alt=\"\" border=\"0\">\n\t<p class=\"system_info\">\n\t\tThe requested URL was not found on this server.\n\t</p>\n\t<hr>\n</body>\n</html>\n\n",
        "headers": {
            "content-type": "text/html;charset=UTF-8",
            "content-length": "400",
            "date": "Mon, 21 Oct 2019 15:52:23 GMT",
            "connection": "close",
            "server": "Apache"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "dev10.demandware.net",
                "port": 443,
                "hostname": "dev10.demandware.net",
                "hash": null,
                "search": null,
                "query": null,
                "pathname": "/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC",
                "path": "/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC",
                "href": "https://dev10.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges/ddevries/../../../../../../../cartridgeC"
            },
            "method": "DELETE",
            "headers": {
                "authorization": "Basic PASSWORD",
                "content-length": 0
            }
        }
    },
    "request": {
        "baseUrl": "https://dev10.demandware.net/on/demandware.servlet/webdav/Sites/Cartridges/ddevries",
        "uri": "/../../../../../../../cartridgeC",
        "auth": {
            "user": "ddevries@dev.com",
            "password": "PASSWORD",
            "pass": "PASSWORD"
        },
        "strictSSL": false,
        "method": "DELETE"
    }
}
	at Request.request [as _callback] (/Users/davisdevries/.vscode/extensions/sqrtt.prophet-1.2.2/out/server/WebDav.js:19:33)
	at Request.self.callback (/Users/davisdevries/.vscode/extensions/sqrtt.prophet-1.2.2/node_modules/request/request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.<anonymous> (/Users/davisdevries/.vscode/extensions/sqrtt.prophet-1.2.2/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:182:13)
	at IncomingMessage.<anonymous> (/Users/davisdevries/.vscode/extensions/sqrtt.prophet-1.2.2/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)
	at endReadableNT (_stream_readable.js:1092:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by SqrTT** [comment]
thank you @davishd 
Could you clarify please, do you have specified cartridges or root folder in your dw.json?

**Comment by rextax** [comment]
Hi, 
Just wanted to emphasize that I have this same problem since few hours with the 1.2.2 prophet version.
Version 1.2.1 works fine.

**Comment by SqrTT** [comment]
Could guys, please, check if issue still persist in v1.2.3?

**Comment by davishd** [comment]
It's working in v1.2.3! Thanks @SqrTT
