### ISSUE TITLE
SFCC VS Code Prophet Upload Error question? (Unable to upload code)

### ISSUE THREAD

**Issue by ccattoNewell** [SqrTT/prophet#214]
# SFCC VS Code Prophet Upload Error question? (Unable to upload code)

Prophet Upload Error

* I am getting an error when uploading code using Prophet extension.
* I am able to upload the code using the node commad `npm run uploadCartridge`. This leads me to believe my credentials are correct & code is working
* I am using the command in the command pallete (cmd+shift+P) Prophet Clean Project/Upload all
* My dw.json file:
````
{
    "hostname": "dev07-realm.demandware.net",
    "username": "email@email.com",
    "password": "P@ssw0rd",
    "code-version": "4.3.8"
}  
````
* My launch.json file is:
````
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.1.0",
    "configurations": [
        {
            "type": "prophet",
            "request": "launch",
            "name": "Attach to Sandbox",
        }
    ]
}
````
* Then in the output read: 
````
Restarting
Using config file '/Users/uy00413/Documents/GitHub/Ecom-commercecloud/ecom-commercecloud/dw.json'
Connection validated successfully
Current active version is: 4.3.8
Start uploading cartridges
Cleanup code version...
[app_storefront_base] Deleting local zip
[app_storefront_base] Zipping
[bc_bazaarvoice] Deleting local zip
[bc_bazaarvoice] Zipping
[app_newell_core] Deleting local zip
[app_newell_core] Zipping
[bc_job_components] Deleting local zip
[bc_job_components] Zipping
[bc_job_components] Deleting remote zip
[app_newell_core] Deleting remote zip
[bc_bazaarvoice] Deleting remote zip
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
Current active version is: 4.3.8
Start uploading cartridges
Cleanup code version...
[app_storefront_base] Deleting local zip
[app_storefront_base] Zipping
[app_newell_core] Deleting local zip
[app_newell_core] Zipping
[bc_bazaarvoice] Deleting local zip
[bc_bazaarvoice] Zipping
[bc_job_components] Deleting local zip
[bc_job_components] Zipping
[bc_job_components] Deleting remote zip
[app_newell_core] Deleting remote zip
[bc_bazaarvoice] Deleting remote zip
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
Current active version is: 4.3.8
Start uploading cartridges
Cleanup code version...
[app_storefront_base] Deleting local zip
[app_storefront_base] Zipping
[bc_bazaarvoice] Deleting local zip
[bc_bazaarvoice] Zipping
[app_newell_core] Deleting local zip
[app_newell_core] Zipping
[bc_job_components] Deleting local zip
[bc_job_components] Zipping
[bc_job_components] Deleting remote zip
[app_newell_core] Deleting remote zip
[bc_bazaarvoice] Deleting remote zip
Error: Error: Not Found 
Trying to re-upload
Connection validated successfully
Current active version is: 4.3.8
Start uploading cartridges
Cleanup code version...
[app_storefront_base] Deleting local zip
[app_storefront_base] Zipping
[bc_bazaarvoice] Deleting local zip
[bc_bazaarvoice] Zipping
[bc_job_components] Deleting local zip
[bc_job_components] Zipping
[app_newell_core] Deleting local zip
[app_newell_core] Zipping
[bc_job_components] Deleting remote zip
[app_newell_core] Deleting remote zip
[bc_bazaarvoice] Deleting remote zip
Error: Error: Not Found 
Error: Error: Not Found 
	at Request.request [as _callback] (/Users/uy00413/.vscode/extensions/sqrtt.prophet-1.0.10/out/server/WebDav.js:15:36)
	at Request.self.callback (/Users/uy00413/.vscode/extensions/sqrtt.prophet-1.0.10/node_modules/request/request.js:186:22)
	at emitTwo (events.js:106:13)
	at Request.emit (events.js:194:7)
	at Request.<anonymous> (/Users/uy00413/.vscode/extensions/sqrtt.prophet-1.0.10/node_modules/request/request.js:1163:10)
	at emitOne (events.js:96:13)
	at Request.emit (events.js:191:7)
	at IncomingMessage.<anonymous> (/Users/uy00413/.vscode/extensions/sqrtt.prophet-1.0.10/node_modules/request/request.js:1085:12)
	at Object.onceWrapper (events.js:293:19)
	at emitNone (events.js:91:20)
	at IncomingMessage.emit (events.js:188:7)
	at endReadableNT (_stream_readable.js:975:12)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
````

## Why do I get this error when trying to upload the code to my sandbox using Prophet? 

Thank you in advance for any & all feedback.

**Comment by SqrTT** [comment]
Hi @ccattoNewell 
Thank you for reporting the issue.

Seems you are using old extension version. If I've guessed correctly, please update to latest (1.2.5) and see if it works (note: new versions available only for new versions of VS Code. so it should be upgraded to last one - 1.41 and up)

**Comment by ccattoNewell** [comment]
@SqrTT  - That was it. I greatly appreciate your quick feedback. The extension really is excellent for SFCC & VS code. I had an old version now I am using 1.2.5 & working smoothly. Thank you!
