### ISSUE TITLE
After last release I get error to find dw.js

### ISSUE THREAD

**Issue by gkkirilov** [SqrTT/prophet#219]
**Describe the bug**
Can't upload cartridges. Crashes with error

Stacktrace
Error: Error: Cannot find module '.....\project\.vscode\dw.js'
	at Function.r [as resolve] (.....vscode\extensions\sqrtt.prophet-1.2.17\dist\extension.js:224:255876)
	at e._subscribe (.....vscode\extensions\sqrtt.prophet-1.2.17\dist\extension.js:142:33880)
	at e._trySubscribe (.....vscode\extensions\sqrtt.prophet-1.2.17\dist\extension.js:16:4559)
	at e.subscribe (.....vscode\extensions\sqrtt.prophet-1.2.17\dist\extension.js:16:4345)
	at .....vscode\extensions\sqrtt.prophet-1.2.17\dist\extension.js:16:5217
	at new Promise (<anonymous>)
	at e.toPromise (.....vscode\extensions\sqrtt.prophet-1.2.17\dist\extension.js:16:5182)
	at f (.....vscode\extensions\sqrtt.prophet-1.2.17\dist\extension.js:16:321251)

**Comment by SqrTT** [comment]
Hi @gkkirilov 
thanks for reporting. Looks like bundled by webpack package can't resolve/open file in filesystem. I'll try to figure out a work around for it.

**Comment by SqrTT** [comment]
could you please check v1.2.18 release, please?

**Comment by gkkirilov** [comment]
@SqrTT Thanks it is working now.
