### ISSUE TITLE
Debugger can't establish connection to sandbox 

### ISSUE THREAD

**Issue by venkatasindhura** [SqrTT/prophet#224]
Hi SqrTT,

Error
 Error
    at H._callback (c:\Users\\.vscode\extensions\sqrtt.prophet-1.2.39\dist\mockDebug.js:211:142961)
    at H.t._callback.t.callback.t.callback (c:\Users\\.vscode\extensions\sqrtt.prophet-1.2.39\dist\mockDebug.js:187:4016)
    at H.emit (events.js:200:13)
    at H.<anonymous> (c:\Users\\.vscode\extensions\sqrtt.prophet-1.2.39\dist\mockDebug.js:187:16713)
    at H.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (c:\Users\\.vscode\extensions\sqrtt.prophet-1.2.39\dist\mockDebug.js:187:15545)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)Disconnecting...
Error

**To Reproduce**
1. Go to 'vs code'
2. Click on 'debug->start debugging' and click on 'attach to sandbox'
3. moveto 'debug console'

**Expected behavior**
Debugger should start.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - VSCode version : 1.42.1
 - The extension version :1.2.39

**Additional context**

**Comment by venkatasindhura** [comment]
I changed below,
prophet debugger version: 1.0.25 and i am getting below error.
Error
 Error
    at Request._callback (**.vscode\extensions\sqrtt.prophet-1.0.25\out\Connection.js:73:35)
    at Request.self.callback (**.vscode\extensions\sqrtt.prophet-1.0.25\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (**.vscode\extensions\sqrtt.prophet-1.0.25\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (**.vscode\extensions\sqrtt.prophet-1.0.25\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)Disconnecting...
Error

**Comment by SqrTT** [comment]
Hi @venkatasindhura 
Thank you for your time to reporting an issue.

Looks like for some reason debugger can't establish connection to sandbox. Could you double check if your password is correct.
I've released v.1.2.40, with more verbose error message for this case. Could you share new error message, please?

PS. Could you please check if your credentials contain special characters like `=`, this may cause an issues like #181

**Comment by gonuguntla9** [comment]
Thank you for you reply.
Yes, its connection issue, I retyped URL, uname, and password and now the connection is successful.
Thank you Again

**Comment by venkatasindhura** [comment]
Thank you for you reply.
Yes, its connection issue, I retyped URL, uname, and password and now the connection is successful.
Thank you Again

**Comment by SqrTT** [comment]
Hi @isabelklings, @cgornez
Could you please confirm this is your issue as well?

**Comment by cgornez** [comment]
> Hi @isabelklings, @cgornez
> Could you please confirm this is your issue as well?

I somehow was able to connect now and not sure if downgrading nodejs to version 10 and prophet to 1.2.5 helps. Those are the changes I made and a couple of restarts :)

**Comment by SqrTT** [comment]
thank you. Closing for now. In case issue still exists please reopen ticket with details.

**Comment by isabelklings** [comment]
Finally I also found my solution:

It was not the password, it was the username, which was case sensitive! My username (Salesforce email address) is capitalized, but in Prophet I typed it in lowercase... that causes this issue.

Thank you.
Best regards
Isabel

**Comment by inturbidus** [comment]
Changing my email to lowercase in dw.json fixed the issue.
