### ISSUE TITLE
Timeout Uploading Cartridges

### ISSUE THREAD

**Issue by jmatos** [SqrTT/prophet#232]
**Describe the bug**
When I start vscode the extension does a clean but then I notice a timeout error occurs and the process starts over - sometimes multiple times.  The result is that it can take a long time for the cartridges to get uploaded to the sandbox.

This is the error I see in the output window in vscode:
**Error: Error: ESOCKETTIMEDOUT
Trying to re-upload cartridge**

**To Reproduce**
1. Start vscode
2 prophet starts uploading 
3. See error in output window and reload starts

**Expected behavior**
No timeout should occur.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MAC OS Catalina
 - VSCode version 
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

 - The extension version [e.g. 22] 1.31

**Additional context**

**Comment by SqrTT** [comment]
hi @jmatos 
seems this is networking issue, please check your connection.

PS. a few people have been reported that sandbox restart helps in some cases, can you please tryout?

**Comment by SqrTT** [comment]
duplicate #225 ?

**Comment by jmatos** [comment]
I have retried and yes it works sometimes and sometimes I still get the error - is there a way to configure the timeout that the extension is using when making network calls?

**Comment by SqrTT** [comment]
unfortunately, currently there are no way to configure it, current value is 15 sec. I believe good trade off. This force user to way 45 sec before give up (15 sec * 3 retries).

Could you please share upload log for such case?

**Comment by SqrTT** [comment]
And are you sure this is the extension issue and not networking? Have you tried to restart sandbox?

**Comment by jmatos** [comment]
yes - I tried restarting sandbox and then it works - but after a short while I get timeout errors again.

So restarting the sandbox is a workaround but not great.

right now my biggest issue is that the debugger no longer works - I can start it but the debugger never activates :(

I'm on a MAC and I have latest vscode and already re-installed both vscode and the extension.

I disabled the sandbox filesystem which was causing vscode search to not work - but right now I'm not sure what I can do to get the debugger to work again - right now I'm back to using eclipse for debugging :(

**Comment by jmatos** [comment]
This is what I have for launch.json file

```{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [    
        {
            "type": "prophet",
            "request": "launch",
            "name": "Attach to Sandbox",
            "trace": true
        }
    ]
}```

**Comment by SqrTT** [comment]
if issue do away after restart this means that most likely the extension is not a source if problem here. And you are trying to treat healthy leg. 

let's don't mix issues into one thread. let's track issue with debugger on appropriate ticket

**Comment by kenzrad** [comment]
This has been happening to me with more frequency lately, and a sandbox restart always does the trick for me. It's pretty annoying, but most likely an issue with the sandboxes.

**Comment by fyratius** [comment]
I am also having this error along with ECONNRESET and ETIMEDOUT errors. However, the behaviour and reproduce steps are a bit different.

We have 13 cartridges in our project and all of the cartridges are being uploaded fine when I open the Visual Studio Code (at least 90% of the time). However, things get ugly when I edit a .js file, as it triggers sgmf-scripts to compile our javascript files along with some map files. When this happens, a bunch of files start uploading and ETIMEDOUT's and ECONNRESET's start appearing in the output in the middle of the upload. After multiple fails, the uploader gives up on uploading individual files, and decides to upload all cartridges instead, but this time ETIMEDOUT's and ESOCKETTIMEDOUT's start appearing after a few cartridges are uploaded successfully.
Uploader tries to re-upload all cartridges a few times, but in the end the following error message is being added to the output, and the uploader gives up:

Error: Error: ETIMEDOUT
	at Timeout.<anonymous> (c:\Users\[removed-intentionally]\.vscode\extensions\sqrtt.prophet-1.3.3\dist\extension.js:202:12578)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)

For now, whenever I edit a .js file, I just restart VS Code, to make the upload work instead of waiting of endless error messages. Fresh upload also faces some errors time to time, but generally it finishes uploading under 1 minute.

Some additional info:
* The problem seem to be happening since early April, I vaguely remember updating VS Code and the extension, but it could be unrelated. Tried different versions of both VS Code and the extension, however the result was the same.
* Restarted the sandbox, did not help unfortunately.
* Had a colleague of mine from a different country connect to my sandbox and do the same procedure, it worked fine.
* Eclipse is also having the same problem, it can upload all cartridges, but not all files after sgmf-scripts do a compilation of .js files and just pops-up an error message related to Socket Time Out and breaks.
* ETIMEDOUT and ECONNRESET pairs seem to be happening more when the extension is trying to upload files with bigger file sizes (800KB+).
* Debugging is indeed quite problematic, I just try to code without it :)

The problem could be related with network connection as the start of the problem is kinda in-line with all these "work from home" situation. I also tried pinging the sandbox while the extension is throwing errors, the average roundtrip was 60ms with one packet being lost over 200 requests. This may indeed be the case, but still not sure unfortunately.

I am dealing with my ISP for the dropped package problem but any other suggestions are also welcome as I am not expecting my ISP to act on it soon.

**Comment by SqrTT** [comment]
how would you suggest to solve networking issue in the extension? As you see, there already bunch of logic to fallback in case of error. (many retries at file level and then on cartridge level and time out is already 15 seconds).
I'm open to suggestions.

**Comment by SqrTT** [comment]
Hi here.
In latest version (v1.3.19) I've cutoff `request` lib and use plain `https` module. Could you monitor behavior of upload, the issue and share feedback if possible, please?

**Comment by ibrianli** [comment]
I've noticed an improvement in the cartridge upload process with your latest update. I no longer run into timeout issues. Prior to the latest update, I would consistently run into timeouts.

**Comment by SqrTT** [comment]
thank you @ibrianli for provided info.

Since basically no activity in the ticket, I'll close it for now. If issue is actual feel free to reopen.

**Comment by prasanna-dev97** [comment]
One solution what I followed is, I deleted static images folder all image files as it had large file size. Then upload cartridges once done then restore all those deleted images . You're good to go now.
