### ISSUE TITLE
Internal Server Error NullPtrException on Sandbox after switching to Account Manager Account

### ISSUE THREAD

**Issue by inturbidus** [SqrTT/prophet#239]
I went from a standard business manager user to a Account Manager user, and now I'm getting an internal server error.

Prophet is able to upload just fine and my settings in launch.config are the same as my dw.json.  I'm able to use my node log tool as well with my Account Manager, but I cannot Attach to Sandbox.  See error and stacktrace below.

```
Error: {
    "_v": "2.0",
    "fault": {
        "type": "InternalServerErrorException",
        "message": "Internal Server Error"
    }
}
 Error: {
    "_v": "2.0",
    "fault": {
        "type": "InternalServerErrorException",
        "message": "Internal Server Error"
    }
}
    at H._callback (/Users/XXXXX/.vscode/extensions/sqrtt.prophet-1.3.3/dist/mockDebug.js:211:144510)
    at H.t._callback.t.callback.t.callback (/Users/XXXXX/.vscode/extensions/sqrtt.prophet-1.3.3/dist/mockDebug.js:187:4016)
    at H.emit (events.js:203:13)
    at H.<anonymous> (/Users/XXXXX/.vscode/extensions/sqrtt.prophet-1.3.3/dist/mockDebug.js:187:16713)
    at H.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (/Users/XXXXXX/.vscode/extensions/sqrtt.prophet-1.3.3/dist/mockDebug.js:187:15545)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)Disconnecting...
Error
```

Stack trace <6c3016fc9c084840f97033a0d6de4a76>
```
java.lang.NullPointerException
	at com.demandware.component.foundation.acl.AccessControlMgrImpl.getAccessRoles(AccessControlMgrImpl.java:274)
	at com.demandware.component.foundation.acl.AccessControlMgrImpl.authorize(AccessControlMgrImpl.java:479)
	at com.demandware.beehive.core.internal.debugger.ScriptDebuggerAuthHandler.checkAccess(ScriptDebuggerAuthHandler.java:150)
	at com.demandware.beehive.core.internal.debugger.ScriptDebuggerAuthHandler.handle(ScriptDebuggerAuthHandler.java:62)
	at com.demandware.core.rest.servlet.RestServlet.prepare(RestServlet.java:221)
	at com.demandware.core.rest.servlet.RestServlet.service(RestServlet.java:286)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at com.demandware.beehive.core.internal.request.DispatcherServlet.service(DispatcherServlet.java:181)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.demandware.beehive.core.internal.request.filter.DetectCharsetFilter.doFilter(DetectCharsetFilter.java:87)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.demandware.beehive.core.internal.request.filter.PCIComplianceFilter.doFilter(PCIComplianceFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.demandware.beehive.core.internal.request.filter.ActivityFilter.doFilter(ActivityFilter.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1181)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[2020-05-06 15:47:04.130 GMT] ERROR http-bio-10.0.35.210-10359-exec-25 com.demandware.core.script.dapi.DebuggerServlet - TEMPORARY ScriptDebu 5454489d406cd76df45d8f1d9d 7215538147830523904 - Failed to process request '/servlet/s/-/dw/debugger/v2_0/client', responding HTTP 500 fault message
```

**Comment by amuliar** [comment]
The same for me.
And I'm still able to start debugger using Eclipse.

**Comment by SqrTT** [comment]
hi @inturbidus 
Thanks for your time and reporting.
Not sure if I can do something here looks like SFCC issue. Try to restart sandbox and double check permissions. If that would not work please file issue to SFCC.

PS. Eclipse, don't use SDAPI for debugging and because of that is not facing the same issue.

**Comment by challmannsf** [comment]
@inturbidus did you login with your AM account at least once ?
I had a similiar issue caused by either

1. not logged in at least once (to active the SB user) with the AM account
2. code version did not exists on SB
3. AM role was not set and therefore the user was not able to manage code versions (login with your user and check if you can view the correct code version)

**Comment by inturbidus** [comment]
Yes I did login with AM and started after enabling AM.  I'll check my user info.

**Comment by inturbidus** [comment]
It seems this problem doesn't occur in Eclipse :(

**Comment by inturbidus** [comment]
@challmannsf which role are you referring to?  I can view the code versions and change them.

**Comment by SqrTT** [comment]
as I said: Eclipse, don't use SDAPI for debugging and because of that is not facing the same issue.

**Comment by SqrTT** [comment]
**challmannsf** are referring to role which allows to use debugger. Assumption is based on provided stack trace (falling on _getAccessRoles_). This seems to be not related to the extension itself but SFCC configs. 
Please double check your credentials and try to change password to new one: we already have issue related to password #181

**Comment by inturbidus** [comment]
I see.  How can I dig into this issue?  I've made a support ticket for it.  For some reason others are not having the same issue with Account Manager.  I have all possible roles and permissions.

**Comment by inturbidus** [comment]
We actually spun up an entirely new sandbox.  BTW I do not have an issue uploading.

**Comment by inturbidus** [comment]
Account Manager Account has All Permissions:

Business Manager Administrator
Business Manager User
Control Center User
CQuotient Configurator User
Log Center User
XChange User

**Comment by inturbidus** [comment]
Reset Account Manager password and same issue.

**Comment by SqrTT** [comment]
Unfortunately, I don't have info how it's made internally. Only SFCC support may help here...
Can anybody else use debugger on your sandbox?

**Comment by inturbidus** [comment]
I know, I'm more logging it for other users who come and see this.  I have asked SFCC support.  User's get same error from their VS Code on another computer.

**Comment by SqrTT** [comment]
> User's get same error from their VS Code on another computer.

I see. 
Is there chance to use different user on the same sandbox (regardless computer), to see if it's related to specific user?

**Comment by challmannsf** [comment]
@inturbidus from your post above

> Yes I did login with AM and started after enabling AM.
I did login to BM to activate the SB user, however, I'm using the AM account in dw.json.

Just to double check: you are able to login into the BM using the account manager credentials (clicking on **Log In With Account Manager**) and those are the same credentials you are entering in dw.json?
When you are in the BM with the account manager credentials you are seeing the code version?
After this try to reupload your code version.

**Comment by inturbidus** [comment]
Yes AM and BM credentials are the same.  Yes I'm able to see code version and switch between them.

**Comment by amuliar** [comment]
so has enebody created SFCC support case to check why debugger API doesn't work with Account Manager user? Unfortunately I can't do that since don't have the access.

**Comment by inturbidus** [comment]
I did create a ticket, but they basically gave me admin and I'm checking to see if it worked.  No technical fix though.

**Comment by amuliar** [comment]
@inturbidus have you resolved the issue?

**Comment by inturbidus** [comment]
Unfortunately no.  We have tried many things, and now they are asking to reprovision which I do not want to do.  We tried making me an account admin, detaching Account Manager from BM account, etc.

**Comment by s-l-ivanov** [comment]
Hello,
I have faced exactly the same issue. The upload works fine and the debugger works fine till yesterday. I have changed the sandbox, check permissions and all was good, but the debugger didn't work. When I changed my username (my Salesforce email address is capitalized), fix the issue.
https://github.com/SqrTT/prophet/issues/224#issuecomment-600490391
I hope that this will resolve your issue too.

**Comment by inturbidus** [comment]
I'll check it out.

**Comment by inturbidus** [comment]
You changed it in Account Manager or in dw.json?

**Comment by s-l-ivanov** [comment]
I changed in the dw.json.

**Comment by inturbidus** [comment]
That worked!!!!!!  And it's reported to SFCC too.

**Comment by MakariukVl** [comment]
> Hello, I have faced exactly the same issue. The upload works fine and the debugger works fine till yesterday. I have changed the sandbox, check permissions and all was good, but the debugger didn't work. When I changed my username (my Salesforce email address is capitalized), fix the issue. [#224 (comment)](https://github.com/SqrTT/prophet/issues/224#issuecomment-600490391) I hope that this will resolve your issue too.

I changed in the dw.json. Writing username in lowercase works for me!
