### ISSUE TITLE
Error: socket hang up  at connResetException

### ISSUE THREAD

**Issue by Christopher-repo** [SqrTT/prophet#245]
**Describe the bug**
for the debug I have all time 
```
Error: socket hang up
 Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at TLSSocket.socketOnEnd (_http_client.js:433:23)
    at TLSSocket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)Disconnecting...
Error: socket hang up
```

no problem for upload a cartridge on my sandbox

**To Reproduce**
1. config launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "prophet",
            "request": "launch",
            "name": "debug_SFRA"
        }
    ]
}
```
2. lanch debug
3. see in the debug consol

```
Error: socket hang up
 Error: socket hang up
    at connResetException (internal/errors.js:559:14)
    at TLSSocket.socketOnEnd (_http_client.js:433:23)
    at TLSSocket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)Disconnecting...
Error: socket hang up
```

and the debug stop

**Screenshots**
![image](https://user-images.githubusercontent.com/28759117/87670676-6b60ec00-c770-11ea-98d5-f52176b94410.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.47.1
 - The extension version 1.3.21

**Comment by SqrTT** [comment]
Hi @Christopher-repo thank you for reporting and sorry for delay. 
Unfortunately, I'm not able to reproduce an issue. So just made blind fix. I didn't come up with better idea then add few retries for debugger requests.

Could you check if issue is actual in v1.3.22, please?

**Comment by SqrTT** [comment]
most likely issue is fixed, if still is actial please reopen.
