### ISSUE TITLE
401 - Authorization Required - This request requires HTTP authentication - after MFA enabled by administrator

### ISSUE THREAD

**Issue by awarberg** [SqrTT/prophet#279]
**Describe the bug**
It is no longer possible to upload to my OnDemand sandbox. The following error is reported in the Output window:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>401 - Authorization Required.</title>
	<link rel="STYLESHEET" type="text/css" href="/waroot/style.css">
</head>
<body>
	<h1>Authorization Required</h1>
	<img src="/waroot/system_arrow.gif" width="21" height="21" alt="" border="0">
	<p class="system_info">
		This request requires HTTP authentication.
	</p>
	<hr>
</body>
</html>


{"options":{"hostname":xxx.sandbox.us01.dx.commercecloud.salesforce.com","uriBase":"/on/demandware.servlet/webdav/Sites/Cartridges/version1","baseUrl":"https://xxx.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.servlet/webdav/Sites/Cartridges/version1","uri":"/","username":"xxx","password":"xxx","headers":{"Depth":1},"method":"PROPFIND"}}
	at IncomingMessage.<anonymous> (c:\Users\xxx\.vscode\extensions\sqrtt.prophet-1.4.13\dist\extension.js:2:218082)
	at Object.onceWrapper (events.js:421:28)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (_stream_readable.js:1220:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**To Reproduce**
This happens whenever I start Visual Studio code or initiate an upload.

**Expected behavior**
Prophet Uploader had no problem uploading to the same OnDemand sandbox prior to MFA activation.

**Screenshots**
This is my user account in Account Manager:

![image](https://user-images.githubusercontent.com/7944743/112318248-21d88180-8cad-11eb-8fcb-b3d29c4e1469.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode version: 1.54.3
 - The extension version: 1.4.13

**Additional context**
I have noticed that I am also no longer able to access the log files on my OnDemand sandbox (or any instance even in the PIG). The logfiles are hosted on Webdav, so maybe it is related to the uploader issue.

**Comment by SqrTT** [comment]
Hi @awarberg 

I believe you already double checked your credentials. But could you also check if your user have permission to upload to webdav.
Or try to use different tool to upload files, let's say Eclipse. to make sure there are no issue on Sandbox side.

PS. My colleagues and me don't have issue with uploading to OnDemand sandboxes.

**Comment by awarberg** [comment]
Yes, I have checked the username + password is correct, but I strongly suspect that MFA has broken my WebDAV access generally as log files are also no longer accessible.

I'm not sure where I would check if I have permission, but I used to have it just a few weeks back - and it is the same OnDemand sandbox.

I only ever used VS Code to upload but I will have to figure out how to setup Eclipse, I guess, as there is currently no way I can upload a new code version to my sandbox. The timing of this is horrible, as I am attempting to build a new business critical feature :-)

**Comment by coltonfenom** [comment]
I am also encountering this issue as of this morning. I'll post a follow up if I find a solution.

**Comment by awarberg** [comment]
I have tried to setup a "Digital Server Connection" in Eclipse but it rejects my credentials (message: "check your User credentials and try again").

**Comment by SqrTT** [comment]
Nothing I can do here. This is SFCC issue. Related to rolled out changes for Account Manager.

There are errors messages in logs:

```log
[2021-03-25 13:20:06.172 GMT] ERROR WebDAVServlet|2043867819 com.demandware.beehive.core.internal.user.UserMgrImpl - TEMPORARY FileServle 2450f9a6d2ad4231740df3d363 1227851996783460352 - Exception during user authentication.
System Information
------------------
RequestID: 2450f9a6d2ad4231740df3d363
SessionType: TEMPORARY
Truncated SessionID: FileServle
ServerName: XXXXXXXXXXXXX
ServerPort: 10052

Request Information
-------------------
URI: /servlet/webdav/Sites/Cartridges/user/
Method: PROPFIND
PathInfo: /Sites/Cartridges/user/
Remote Address: 00.00.00.00

Request Parameters
------------------

Stack trace <15019d2a916a3eb15497ed7f49dc56b0>
com.demandware.beehive.core.capi.common.SystemException: Exception occured while connecting with Account Manager.
	at com.demandware.beehive.core.am.AccountManagerClient.authenticate(AccountManagerClient.java:90)
	at com.demandware.beehive.core.internal.user.UserMgrImpl.authenticateSSOUserViaRPC(UserMgrImpl.java:2569)
	at com.demandware.beehive.core.internal.user.UserMgrImpl.doAuthenticateImpl(UserMgrImpl.java:1674)
	at com.demandware.beehive.core.internal.user.UserMgrImpl.authenticateImpl(UserMgrImpl.java:1419)
	at com.demandware.beehive.core.internal.user.UserMgrImpl.lambda$authenticate$4(UserMgrImpl.java:1376)
	at com.demandware.beehive.core.internal.security.TimedExecution.execute(TimedExecution.java:52)
	at com.demandware.beehive.core.internal.user.UserMgrImpl.authenticate(UserMgrImpl.java:1376)
	at com.demandware.beehive.core.internal.webdav.FileServlet.authorizeByBasic(FileServlet.java:746)
	at com.demandware.beehive.core.internal.webdav.FileServlet.authorize(FileServlet.java:678)
	at com.demandware.beehive.core.internal.webdav.WebdavServlet.authorize(WebdavServlet.java:482)
	at com.demandware.beehive.core.internal.webdav.FileServlet.checkAccess(FileServlet.java:632)
	at com.demandware.beehive.core.internal.webdav.WebdavServlet.service(WebdavServlet.java:399)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.CodeUploadTrackingFilter.doFilter(CodeUploadTrackingFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.MetricTrackingFilter.doFilter(MetricTrackingFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.PCIComplianceFilter.doFilter(PCIComplianceFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.demandware.beehive.core.internal.request.filter.ActivityFilter.doFilter(ActivityFilter.java:311)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:381)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.demandware.core.rpc.client.CommunicationException: i/o exception invoking [user_authentication_protocol3.authenticate(),  https://account-internal.demandware.com:443/_dw/rpc/1/user_authentication_protocol3/authenticate/1], cause: javax.net.ssl.SSLHandshakeException: Received fatal alert: decrypt_error
	at com.demandware.core.rpc.http.HttpRpcClientChannel.sendData(HttpRpcClientChannel.java:589)
	at com.demandware.core.rpc.http.HttpRpcClientChannel.sendData(HttpRpcClientChannel.java:87)
	at com.demandware.core.rpc.client.AbstractClientChannel.uncachedSendMessage(AbstractClientChannel.java:523)
	at com.demandware.core.rpc.client.AbstractClientChannel.cachedSendMessage(AbstractClientChannel.java:479)
	at com.demandware.core.rpc.client.AbstractClientChannel.syncSendMessage(AbstractClientChannel.java:401)
	at com.demandware.core.rpc.client.AbstractClientChannel.invoke(AbstractClientChannel.java:169)
	at com.demandware.core.rpc.client.GenericProtocolStub.invoke(GenericProtocolStub.java:225)
	at com.demandware.core.rpc.client.GenericProtocolStub.protocolJavaInvoke(GenericProtocolStub.java:213)
	at com.demandware.core.rpc.client.ProtocolStubFactory$ProtocolHandler.invoke(ProtocolStubFactory.java:147)
	at com.sun.proxy.$Proxy141.authenticate(Unknown Source)
	at com.demandware.am.client.ecom.CachingUserAuthenticator3.delegateAuthenticate(CachingUserAuthenticator3.java:131)
	at com.demandware.am.client.ecom.CachingUserAuthenticator3.performAuthentication(CachingUserAuthenticator3.java:124)
	at com.demandware.am.client.ecom.CachingUserAuthenticator3.authenticate(CachingUserAuthenticator3.java:83)
	at com.demandware.beehive.core.am.AccountManagerClient.authenticate(AccountManagerClient.java:85)
	... 42 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: decrypt_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2020)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.demandware.core.rpc.http.HttpRpcClientChannel.sendData(HttpRpcClientChannel.java:472)
	... 55 more
```

**Comment by awarberg** [comment]
@SqrTT I agree, this seems to be caused by the MFA changes on CC. However, Prophet Debugger (and Eclipse) may eventually need to add support for the "second factor" as MFA is rolled out to all CC orgs.

**Comment by SqrTT** [comment]
I believe this is temporary outage and SFCC deliver fix soon.

**Comment by awarberg** [comment]
@SqrTT Perhaps the organization settings are different? This is our settings:

![image](https://user-images.githubusercontent.com/7944743/112487129-c70e5b00-8d7c-11eb-9d87-9abb6e3d93b9.png)

**Comment by awarberg** [comment]
I have been in touch with demandware support. They suggest that it is no longer possible to access WebDAV using a username and password and I must instead create an access key. But how do I plug that into dw.json? It seems to only take the username and password:

https://documentation.b2c.commercecloud.salesforce.com/DOC1/index.jsp?topic=%2Fcom.demandware.dochelp%2Fcontent%2Fb2c_commerce%2Ftopics%2Fadmin%2Fb2c_access_keys_for_business_manager.html

**Comment by SqrTT** [comment]
thanks for info. the question is not about how plug it into `dw.`json but how is should be used. How it should be passed to webdav and debugger api...

**Comment by SqrTT** [comment]
just curious, does Eclipse working with new access tokens?

**Comment by SqrTT** [comment]
anyway exception in logs doesn't look like this is related to "access keys"

**Comment by clstopher** [comment]
I haven't worked with an Access Key yet - But I've directed a few people to try it and it has worked for them; Once you generate the access key, it is an alternative for your password and you just drop it into dw.json as if it were.

To create Access Key - Log into BM, click your name in the upper right corner. On the user edit page (only when navigated this way, not when navigated to in BM Users list page), you have a button to manage your access keys.

I created one earlier, and one advantage is that they last a year instead of 3 months; Also an advantage in not having a super useful and all-powerful password stored in plaintext on your filesystem.  Disadvantage that I see is that they appear to be instance specific.

**Comment by awarberg** [comment]
@clstopher Thanks a bunch! It works by replacing the password in `dw.json` with the access key.

**Navigation to the Access Keys menu after clicking your profile name in Business Manager**
![image](https://user-images.githubusercontent.com/7944743/112590774-ab9a6300-8e03-11eb-9cfb-39574f7c2fe7.png)

**The generated access key**
![image](https://user-images.githubusercontent.com/7944743/112590925-e2707900-8e03-11eb-9e3a-220c15a8172e.png)

**[dw.json]**
```
{
  "username": "xxx",
  "password": "<insert the access key here>",
  "hostname": "xxx.sandbox.us01.dx.commercecloud.salesforce.com",
  "code-version": "version1",
  "cartridge": ["xxx"]
}
```

**Comment by SqrTT** [comment]
thank you very much @awarberg and @clstopher

**Comment by taehyunlim** [comment]
@awarberg - Just wanted to say thank you for posting this solution, this saved my day big time!

**Comment by SinzianaS** [comment]
Many thanks to @awarberg and @clstopher, finally solved my error uploading cartridges.
