### ISSUE TITLE
Error: SyntaxError: Unexpected token ​ in JSON at position

### ISSUE THREAD

**Issue by Roohi-Jain** [SqrTT/prophet#318]
Hi @SqrTT,
I am getting the following SyntaxError in VS Code OUTPUT:

VSCode Node version: v14.16.0
Starting...
Error: SyntaxError: Unexpected token ​ in JSON at position 326
Error: SyntaxError: Unexpected token ​ in JSON at position 326
	at JSON.parse (<anonymous>)
	at e._subscribe (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:225374)
	at e._trySubscribe (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:38613)
	at e.subscribe (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:38399)
	at u (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:50549)
	at t._innerSub (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:65416)
	at t._tryNext (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:65305)
	at t._next (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:65128)
	at t.next (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:45242)
	at ReadStream.<anonymous> (/Users/roobenga/.vscode/extensions/sqrtt.prophet-1.4.27/dist/extension.js:2:224900)
	at ReadStream.emit (events.js:315:20)
	at emitCloseNT (internal/streams/destroy.js:87:10)
	at processTicksAndRejections (internal/process/task_queues.js:79:21)

This is the structure of my dw.json file:
{
    "hostname": "***", 
    "username": "***", 
    "password": "***", 
    "cartridge":[
        "***",
        "***"
    ],
    "cartridgesPath":"***",
    "code-version":"***"
}​​​​​​

Using Visual Studio Code Version:- 1.65.2 and Prophet Debugger:- v1.4.27 and Node version - v14.19.1
This issue is coming only on MAC.
I have tried alot many things but nothing worked so far.
Any help is much Appreciated.

**Comment by SqrTT** [comment]
Hi @Roohi-Jain 
Have you tried to validate your dw.json via tools like https://jsonformatter.curiousconcept.com/ ?

also please make sure correct file is used. Make sure you have only one dw,json or dw.js file

PS: this is not related to your issue but most likely you don't need `cartridge` property in your dw.json. Nowadays the extension can recognize cartridges without this property.
