### ISSUE TITLE
sandbox crashed once hitting the breakpoint

### ISSUE THREAD

**Issue by zsardone** [SqrTT/prophet#65]
I just installed prophet debugger and each time I hit the breakpoint, I click on step over a couple of times, it would hang the site, then if I terminate the debugger, the sandbox would crash. I had to restart it manually. Our network is really slow today, I hope that is the root cause. We will see another day how this works. 

Steps to reproduce : 
1. Turn on debugger, hit the breakpoint
2. at the debug console, type a few variables, sometime it respond with a value other times it does not.
3. click on Step over once it hits the debugging point. 

"configurations": [  
      {  
          "type": "prophet",  
          "request": "launch",  
          "name": "Attach to sandbox",  
          "hostname": "xx.demandware.net",  
          "username": "xxx",  
          "password": "xxx",  
          "codeversion": "version1",  
          "cartridgeroot": "auto",  
          "workspaceroot": "${workspaceRoot}/cartridges/xx/"  
      }  
    ]

**Comment by zsardone** [comment]
JSON.stringify(req.querystring)
-> ReferenceError: "req" is not defined. ([DEBUGGER EXPR: JSON.stringify(req.querystring)]#1)
element
not available
Error: Internal Server Error
 Error: Internal Server Error
    at Request.request [as _callback] (/Users/xxxx/.vscode/extensions/SqrTT.prophet-0.9.7/out/Connection.js:41:35)
    at Request.self.callback (/Users/zsardone/.vscode/extensions/SqrTT.prophet-0.9.7/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/zsardone/.vscode/extensions/SqrTT.prophet-0.9.7/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/zsardone/.vscode/extensions/SqrTT.prophet-0.9.7/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
Error: Internal Server Error Please restart debugger

**Comment by SqrTT** [comment]
hi @zsardone 
This is known issue #42 
Unfortunately there no way to stable reproduce and fix. :(

closing as duplicate and tracking there.
