### ISSUE TITLE
Debugger breaks when opening LinkedHashMap type in variables

### ISSUE THREAD

**Issue by gkkirilov** [SqrTT/prophet#71]
When I stop the debugger at a breakpoint my debugger errors when I try to open LinkedHashMap but others variables open with no problem.
I use StoreMgr.searchStoresByCoordinates() to get my LinkedHashMap.

Here is the error in console
Error: Internal Server Error
    at Request.request [as _callback] (C:\Users\Argon\.vscode\extensions\SqrTT.prophet-0.9.9\out\Connection.js:41:35)
    at Request.self.callback (C:\Users\Argon\.vscode\extensions\SqrTT.prophet-0.9.9\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\Argon\.vscode\extensions\SqrTT.prophet-0.9.9\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\Argon\.vscode\extensions\SqrTT.prophet-0.9.9\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)

**Comment by SqrTT** [comment]
Could you please check if the issue persists in v.0.10.0 (with SDAPI 2.0)?

**Comment by gkkirilov** [comment]
@SqrTT Its fixed
