### ISSUE TITLE
Debugger breaks on accessing a HashMap variable

### ISSUE THREAD

**Issue by nikegp** [SqrTT/prophet#95]
Hi!

Every time I try to expand a HashMap variable the debugger breaks with the following exception

```
Error: Internal Server Error
 Error: Internal Server Error
    at Request.request [as _callback] (/home/nike/.vscode/extensions/SqrTT.prophet-1.0.1/out/Connection.js:49:35)
    at Request.self.callback (/home/nike/.vscode/extensions/SqrTT.prophet-1.0.1/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/home/nike/.vscode/extensions/SqrTT.prophet-1.0.1/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/home/nike/.vscode/extensions/SqrTT.prophet-1.0.1/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
```

Prophet 1.0.1. Let me know if I can help to debug it further

PS. Thanks for the debugger, it's awesome

**Comment by SqrTT** [comment]
Could you please share a some snippet so I would able to reproduce the issue?

![image](https://user-images.githubusercontent.com/1271300/38079708-42e6a33c-3348-11e8-9ec0-bdc05c8b2491.png)

**Comment by nikegp** [comment]
It seems it fails on HashMaps returned from Basket->getAllProductQuantities if a basket has an option product. I test on SG with this item https://d.pr/i/bcFzMH and if I add it without warranty I can expand the HashMap. If I add the product with warranty the debugger fails with the error. Hope this helps

**Comment by julienphilippe** [comment]
i tested with Hashmap it's working correctly
